{
  "name": "Release",
  "on": {
    "release": {
      "types": [
        "published"
      ]
    }
  },
  "env": {
    "CARGO_TERM_COLOR": "always"
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "env": {
        "CARGO_REGISTRY_TOKEN": "${{ secrets.CARGO_REGISTRY_TOKEN }}"
      },
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "name": "rustc",
          "run": "rustc --version"
        },
        {
          "name": "cargo",
          "run": "cargo --version"
        },
        {
          "name": "Check format",
          "run": "cargo fmt --check"
        },
        {
          "name": "Check",
          "run": "cargo check"
        },
        {
          "name": "Build",
          "run": "cargo build"
        },
        {
          "name": "Test",
          "run": "cargo test"
        },
        {
          "name": "Publish to crates.io",
          "working-directory": "lm-proxy",
          "run": "cargo publish"
        }
      ]
    }
  }
}